name: weak_cache
description: Weak cache that uses weak references for holding values.
version: 1.0.0
homepage: https://github.com/Zekfad/weak_cache
repository: https://github.com/Zekfad/weak_cache
issue_tracker: https://github.com/Zekfad/weak_cache/issues
# documentation: https://pub.dev/documentation/weak_cache/latest/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
