name: weak_cache
description: >
  Weak cache that uses weak references for holding values.
  Implements full Map interface including keys and values iteration.
version: 2.0.1
homepage: https://github.com/Zekfad/weak_cache
repository: https://github.com/Zekfad/weak_cache
issue_tracker: https://github.com/Zekfad/weak_cache/issues
# documentation: https://pub.dev/documentation/weak_cache/latest/
topics:
  - cache
  - memory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.25.2
  zekfad_lints: ^2.0.0
